### ISSUE TITLE
Crash when adding a new category

### ISSUE THREAD

**Issue by alpha4041** [f33lnothin9/cashsense#2]
The app crashes when adding a new category. After opening it again, the app crashes once accessing the category tab.

Device:
- Xiaomi 11 Lite 5G NE
- ROM: Evolution OS 8.2 (Android 14)

Logs:
[26_02-08-40-36_810.log](https://github.com/f33lnothin9/cashsense/files/14401300/26_02-08-40-36_810.log)

Screen recording:
https://file.io/IeucXt0LYp7E

**Comment by f33lnothin9** [comment]
I fixed this issue, the application crashes when a category is created without selecting a different icon for it.
